version: '3.9'
services:
  serverprod:
    container_name: serverprod
    build:
      context: ./api
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /usr/src/app/
  clientprod:
    container_name: clientprod
    build:
      context: ./webapp
      dockerfile: dockerfile
    ports:
      - "80:80"
    volumes:
      - /usr/src/app/
    depends_on:
      - serverprod