# Development
FROM node:latest as development

WORKDIR /usr/src/app

COPY ./package*.json /usr/src/app/

RUN npm install

RUN npm install -g @angular/cli

COPY . .

RUN npm run build

# Production
FROM node:latest

WORKDIR /usr/src/app

COPY ./package*.json /usr/src/app/

RUN npm ci

COPY . .

FROM nginx:latest

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=development /usr/src/app/dist/webapp /usr/share/nginx/html

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]